{% set version = "2025.07.22" %}

package:
  name: khronos-opencl-icd-loader
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/refs/tags/v{{ version }}.zip
    sha256: db29e0028ff1ee5f166ce726ad046375233bb530ea98c00e05f4b1e517343771
    patches:
      - no_check_integrity_win.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("khronos-opencl-icd-loader", max_pin=None) }}

  # We've got ocl-icd on Linux which has better debugging support
  # and was used before khronos adopted an open source license.
  # new versions don't support older MSVC
  skip: true  # [linux or (win and vc<14)]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python
    - make   # [not win]
    - ninja  # [win]
  host:
    - opencl-headers ={{ version }}
  run:
    - {{ pin_compatible("opencl-headers", max_pin=None) }}


test:
  requires:
    - pkg-config
  commands:
    - if not exist %LIBRARY_INC%\\CL\\cl.h exit 1       # [win]
    - if not exist %LIBRARY_BIN%\\OpenCL.dll exit 1     # [win]
    - test -f $PREFIX/include/OpenCL/cl.h               # [osx]
    - test -f $PREFIX/include/CL/cl.h                   # [linux]
    - test -f $PREFIX/lib/libOpenCL${SHLIB_EXT}         # [unix]
    - cllayerinfo
    - pkg-config OpenCL --libs --cflags

    # This crashes with a segfault. Likely for a lack of ICD to talk to.
    # - cd %SRC_DIR%/build && ctest
  # downstreams:
  #   # Run the pyopencl test suite
  #   - pyopencl

about:
  home: https://registry.khronos.org/OpenCL/
  license: Apache-2.0
  license_file: LICENSE
  summary: A driver loader for OpenCL
  dev_url: https://github.com/KhronosGroup/OpenCL-ICD-Loader
  doc_url: https://registry.khronos.org/OpenCL/
extra:
  recipe-maintainers:
    - inducer
    - isuruf
