{% set version = "978b4b3a29a3aebc86ce9315d5c5963e88722d03" %}
{% set sha256 = "6c79fddd59e92182d7bc9048415b51e60e49f952b11eeffd69cccb3081359f78" %}

{% set headers_version = "0d5f18c6e7196863bc1557a693f1509adfcee056" %}
{% set headers_sha256 = "476bf3611ca3b105565344e75cd3c170ce5961c7c9745181959c9c7f3541eff2" %}

package:
  name: khronos-opencl-icd-loader
  version: 2019.07.12

source:
  - url: https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/{{ version }}.zip
    sha256: {{ sha256 }}

  - url: https://github.com/KhronosGroup/OpenCL-Headers/archive/{{ headers_version }}.zip
    sha256: {{ headers_sha256 }}
    folder: inc

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("khronos-opencl-icd-loader", max_pin=None) }}

  # We've got ocl-icd on Linux. No need to use
  # this ... fantastic piece of software ... anywhere else.
  # new versions don't support older MSVC
  skip: true  # [linux or (win and vc<14)]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - python
    - make   # [not win]
    - ninja  # [win]
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_INC%\\CL\\cl.h exit 1       # [win]
    - if not exist %LIBRARY_BIN%\\OpenCL.dll exit 1     # [win]
    - test -f $PREFIX/include/OpenCL/cl.h               # [osx]
    - test -f $PREFIX/include/CL/cl.h                   # [linux]
    - test -f $PREFIX/lib/libOpenCL${SHLIB_EXT}         # [unix]

    # This crashes with a segfault. Likely for a lack of ICD to talk to.
    # - cd %SRC_DIR%/build && ctest

about:
  home: https://www.khronos.org/registry/cl/
  dev_url: https://github.com/KhronosGroup/OpenCL-ICD-Loader
  license: Apache v2.0
  license_file: LICENSE
  summary: A driver loader for OpenCL

extra:
  recipe-maintainers:
    - inducer
    - isuruf
