travis:
  secure:
    BINSTAR_TOKEN: QSarfXWIDuZuMyODTfb3e0l9aKpVlyLDoKZIQn1OzTBZFFVqQVDUz3V9bi771uiSbIjRbIqfy29n8VknmsspxPUGJblXuBt/W1XWPEOWGlxP+swmyBsPhzIShR9i+lLxztTOUrLs7xiaphLzwKXDZzQzDq4i1rnoyi35fN9oPlqncT461Z936JhVgbzF1oQ7U9NQ4Ft3+OJRZ3EpUWEVcAYux1ro16DwpkWs2+GqpLMzUfKMl9nusKwMVWZNYXCfbxJ1f3RMFuecugC2X8zENxJIigzGVbIQdMNuXsVj2WrmDBN3mwkabnY4VnBhk3zDWy3EaPxj/ETurTXRe2o3DBjgJ5uTwdNlPBvPVK4xEjRh8jLDF3cuc+fyuma2RkzAPX+zRxuBZToItQ8WKtFFyCP1gfa72wsoR+Or6p97Zwr4Nk3H48TSwPexNJ+c4yZfq52noxPMlAHEgxNU8F9DhmyOrvK68MhWPu83VaZU1TlAXaHqfptb5ibRqtHsaFkrKqEAQfKEMO5xIBNvE8YU+Tl1OOxRbF20luWYPoGryx14MloKk8TfGRuduD9JKEyV8RwchiMY4eKEYpJVaFmxhDeCDjdZvtK2pIIpSCH0NeEp98ZXgzvtkhtBuhubJC0Sno2/3mXFXJLt6ZtXpf8yxLWaCCGWueLCewQ0papoP9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
