travis:
  secure:
    BINSTAR_TOKEN: PJVKaAAC59WoiK7O5CagDgGKM9exF2dIwd96al1iwWpxZPdB5gHc43eynxBkrrLF4Jzj6PgWFc2aHPVApGgFmDTX2mybAkpd1lKFOxgjU0m11DrmNEDnheOn486p/rdeWC7vgQFs88ypRFNQRv9CHmwj8RASu3WiDyGJ/ap44KMktwBcAsCPDOtH/vVXhNXRUEPmymUwww7X/adJH3kgZcMx7rhcPqe0m26Pvs4bMKEVoiN6eqQfh+JHQO4YRr2pN5Ol4MXjWwMc5pOngdU2yxKxWlOoo3vOHz6tFaN6T3xrKHDQhaJIRQtcFvo4ffGfkO+4qHpt3dtvv1Qc0wvsxIJyXkXzPwUHgu7m19iSOJrzSSWfCb+9+wX3Qv4WmePX8MebDbFjrDmB1Krdw1MInS3zUOhNFKOFFwZVV/DDkUiXf0gUv4XMvAfN9eATEfwTgn+VHxRRSouSEh/g3PdyqYb1gjEFIIo8gNjhLvDUL+Hs0hMeHyVz0qe1Bj5dGjIuFM2jZX3WR7TEfUB+IDnLs6oc0JRIn1CyHN3RHnuT/aTBrxMq/1PEzmz8aJaUp9EW7bQNxoYot0LjthZPvzp+jgpD8F4iY7AuS3MBtBi8jcmeh5XyA6fGL20J2NN/rF2qTZpiW7cIIdqnE7LBzeukSUfetunnBXkf2Nud51sV/fI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
